# Generated by Django 4.1.7 on 2023-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='host',
            new_name='name',
        ),
    ]
